---
# Configuration file for the installation process

# Commented lines will default to false

# ???
setup_process:
  user_interaction: 1

internet_connection:
  # wifi: 1
  # ssid: AnSSID
  # password: APassword

partitions:
  swap: 1
  swap_location: "/swapfile"
  additional_partitions: 
    - partition_name: "/dev/sda3"
      mountpoint: "/mnt"
      format: ext4
    - partition_name: "/dev/sda4"
      mountpoint: "/mnt/home"
      format: no

localization:
  timezone: Europe/Bucharest
  locale: en_US.UTF-8 UTF-8
  locale_lang: en_US.UTF-8 

network_config:
  hostname: myhostname

users:
  root_password: my_Root-passWord
  regular_users:
  - username: yourusername
    groups: "power,storage,wheel"
    password: 'a-password'

packages: 
  # packages_tarball_url : myexample.com


bootloader:
  bootloader_install_commands:
    - grub-install
    - mount

homedir_configs:
  # homedir_tarball_url: myexample.com
  # commands:
  # - xdg-user-dirs-update
